### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by jmls** [DineroRegnskab/ngx-virtual-scroll#4]
I get no errors when running, and I see some data appear, but I can't scroll.

                <ul class="virtual-scroll-container"
                    [ngxVirtualScrollFor]="filteredTasks"
                    [containerHeight]="780"
                    [defaultItemHeight]="65"
                    (containerHeight$)="height = $event"
                    (sliced$)="slice = $event">

                    <div [style.height.px]="height">
                        <li class="issue"   *ngFor="let issue of slice.collection">

There are 2 issues that I see:

#1 if I use the `<div [style.height.px]="height">` as suggested. I get a great stonking sized div : for approx 2000 items, the div has a height of `height: 130520px;` ;)

if I remove the div, the height of the `ul` container is 946 px;

however, 

#2 the first set of data appears, but I cannot scroll ... so I can't get to any other entries in the list

**Comment by mikkeldamm** [comment]
@jmls as I understand correctly, you are removing the `<div [style.height.px]="height">` ?
If thats the case then it won't work, because that container simulates the height if all the items were rendered and therefor make it possible for the directive to listen for the scroll event and render the items accordingly. 

Closing it here
