### ISSUE TITLE
Will the event be implemented: scroll reached the bottom?

### ISSUE THREAD

**Issue by NeoSimvolist** [DineroRegnskab/ngx-virtual-scroll#8]

**Comment by mikkeldamm** [comment]
@NeoSimvolist sorry for the late answer. 
That event is not something that we have right now, and are not planning to add it because we our self don't have that use case.

But you are very welcome to create a pull request, and I would happily review and merge it 😃 

Just on the top of my head, I think it could be done by doing something like this:
```
@Output() reachedBottom$: EventEmitter<void> = new EventEmitter<void>();
...
private _haveReachedBottom = false;
```

Then in executeSlicing method:
```
if ((from + slicedCollection.length) === this._originalCollection.length && !this._haveReachedBottom) {
    this._haveReachedBottom = true;
    this.reachedBottom$.next();
} else {
    this._haveReachedBottom = false;
}
```

But probably a bit prettier than that 😉
