### ISSUE TITLE
Scroll on window causing thumb-button to jump back and forth randomly

### ISSUE THREAD

**Issue by shusain** [DineroRegnskab/ngx-virtual-scroll#9]
![window-scroll-issue](https://user-images.githubusercontent.com/523230/39646424-03d0e624-4fa1-11e8-8cba-bdf6d7200583.gif)

Having an issue when attempting to use the component when scrolling an entire window with contents above the scrollable elements.  If this isn't a supported use case please let me know.

**Comment by shusain** [comment]
Found I had an issue in my markup that was in part to blame here but still seeing a lot of flickering after fixing the attributes.  Will attempt to recreate on stackblitz to have a live sample of the issue to see if I missed something.

**Comment by mikkeldamm** [comment]
@shusain its because you are missing the style property `position: absolute;` on the `<li>` tag.
https://github.com/DineroRegnskab/ngx-virtual-scroll/blob/master/integration/app/window-scroll/window-scroll.component.ts#L41

The reason why we choose to make the items inside the virtual scroll container absolute positioned, is because we found out the browsers repaint were quicker than if relative.

So by adding that style property to your `li` element, then it should work 😃
